# Introduction to Pandas
## 23/7/24

In [22]:
import pandas as pd

In [23]:
print(pd.__version__)

2.2.2

In [24]:
mydataset = {'Brand':["McLaren","Ferrari","Audi"],'Colour':["Silver","Red","Blue"]}
myvar = pd.DataFrame(mydataset)
print(myvar)

     Brand  Colour
0  McLaren  Silver
1  Ferrari     Red
2     Audi    Blue

In [25]:
myvar.describe()
myvar.info()
print(myvar.loc[[0,1]])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Brand   3 non-null      object
 1   Colour  3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes
     Brand  Colour
0  McLaren  Silver
1  Ferrari     Red

In [26]:
data = {"Calories": [420, 380, 390],"Duration": [50, 40, 45]}
print(type(data))
df = pd.DataFrame(data)
print(df)
print(type(df))

<class 'dict'>
   Calories  Duration
0       420        50
1       380        40
2       390        45
<class 'pandas.core.frame.DataFrame'>

In [27]:
print(df.loc[0])

Calories    420
Duration     50
Name: 0, dtype: int64

In [28]:
print(df.loc[[0,1]])

   Calories  Duration
0       420        50
1       380        40

In [29]:
df.describe()

         Calories  Duration
count    3.000000       3.0
mean   396.666667      45.0
std     20.816660       5.0
min    380.000000      40.0
25%    385.000000      42.5
50%    390.000000      45.0
75%    405.000000      47.5
max    420.000000      50.0

In [30]:
df.iloc[1]

Calories    380
Duration     40
Name: 1, dtype: int64

In [31]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [32]:
df.info

<bound method DataFrame.info of    Calories  Duration
0       420        50
1       380        40
2       390        45>

In [33]:
df.mean()

Calories    396.666667
Duration     45.000000
dtype: float64

In [34]:
df.dropna()

   Calories  Duration
0       420        50
1       380        40
2       390        45

In [35]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
df1 = pd.DataFrame(data)
print(df1)

     Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd

In [36]:
print(df1[['Name', 'Qualification']])

     Name Qualification
0     Jai           Msc
1  Princi            MA
2  Gaurav           MCA
3    Anuj           Phd

In [37]:
print(df1[['Name','Age']])

     Name  Age
0     Jai   27
1  Princi   24
2  Gaurav   22
3    Anuj   32

In [38]:
import os

In [39]:
os.getcwd()

'/Users/kaivanshah/Documents/Data_Analysis/Day_To_Day'

In [40]:
print(pd.options.display.max_rows)

9999

In [41]:
pd.options.display.max_rows = 9999
print(pd.options.display.max_rows)

9999

In [42]:
dataf = pd.read_csv('salary_data.csv')
dataf

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [43]:
print(dataf)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [44]:
dataf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [45]:
dataf.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [46]:
import statistics as sts
print(sts.mode(dataf['Salary']))
print(sts.mean(dataf['Salary']))
print(sts.median(dataf['Salary']))

39343.0
76003.0
65237.0

In [47]:
dataf2 = pd.read_csv('Advertising.csv')
dataf2

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
5             6    8.7   48.9       75.0    7.2
6             7   57.5   32.8       23.5   11.8
7             8  120.2   19.6       11.6   13.2
8             9    8.6    2.1        1.0    4.8
9            10  199.8    2.6       21.2   10.6
10           11   66.1    5.8       24.2    8.6
11           12  214.7   24.0        4.0   17.4
12           13   23.8   35.1       65.9    9.2
13           14   97.5    7.6        7.2    9.7
14           15  204.1   32.9       46.0   19.0
15           16  195.4   47.7       52.9   22.4
16           17   67.8   36.6      114.0   12.5
17           18  281.4   39.6       55.8   24.4
18           19   69.2   20.5       18.3   11.3
19           20  147.3   23.9       19.1   14.6
20           21  218.4   27.7       53.4   18.0
21           22  237.4    5.1       23.5   12.5
22           23   13.2   15.9       49.6    5.6
23           24  228.3   16.9       26.2   15.5
24           25   62.3   12.6       18.3    9.7
25           26  262.9    3.5       19.5   12.0
26           27  142.9   29.3       12.6   15.0
27           28  240.1   16.7       22.9   15.9
28           29  248.8   27.1       22.9   18.9
29           30   70.6   16.0       40.8   10.5
30           31  292.9   28.3       43.2   21.4
31           32  112.9   17.4       38.6   11.9
32           33   97.2    1.5       30.0    9.6
33           34  265.6   20.0        0.3   17.4
34           35   95.7    1.4        7.4    9.5
35           36  290.7    4.1        8.5   12.8
36           37  266.9   43.8        5.0   25.4
37           38   74.7   49.4       45.7   14.7
38           39   43.1   26.7       35.1   10.1
39           40  228.0   37.7       32.0   21.5
40           41  202.5   22.3       31.6   16.6
41           42  177.0   33.4       38.7   17.1
42           43  293.6   27.7        1.8   20.7
43           44  206.9    8.4       26.4   12.9
44           45   25.1   25.7       43.3    8.5
45           46  175.1   22.5       31.5   14.9
46           47   89.7    9.9       35.7   10.6
47           48  239.9   41.5       18.5   23.2
48           49  227.2   15.8       49.9   14.8
49           50   66.9   11.7       36.8    9.7
50           51  199.8    3.1       34.6   11.4
51           52  100.4    9.6        3.6   10.7
52           53  216.4   41.7       39.6   22.6
53           54  182.6   46.2       58.7   21.2
54           55  262.7   28.8       15.9   20.2
55           56  198.9   49.4       60.0   23.7
56           57    7.3   28.1       41.4    5.5
57           58  136.2   19.2       16.6   13.2
58           59  210.8   49.6       37.7   23.8
59           60  210.7   29.5        9.3   18.4
60           61   53.5    2.0       21.4    8.1
61           62  261.3   42.7       54.7   24.2
62           63  239.3   15.5       27.3   15.7
63           64  102.7   29.6        8.4   14.0
64           65  131.1   42.8       28.9   18.0
65           66   69.0    9.3        0.9    9.3
66           67   31.5   24.6        2.2    9.5
67           68  139.3   14.5       10.2   13.4
68           69  237.4   27.5       11.0   18.9
69           70  216.8   43.9       27.2   22.3
70           71  199.1   30.6       38.7   18.3
71           72  109.8   14.3       31.7   12.4
72           73   26.8   33.0       19.3    8.8
73           74  129.4    5.7       31.3   11.0
74           75  213.4   24.6       13.1   17.0
75           76   16.9   43.7       89.4    8.7
76           77   27.5    1.6       20.7    6.9
77           78  120.5   28.5       14.2   14.2
78           79    5.4   29.9        9.4    5.3
79           80  116.0    7.7       23.1   11.0
80           81   76.4   26.7       22.3   11.8
81           82  239.8    4.1       36.9   12.3
82           83   75.3   20.3       32.5   11.3
83           84   68.4   44.5       35.6   13.6
84           85  213.5   43.0       33.8   21.7
85           86  193.2   18.4       65.7   15.2
86           87   76.3   27.5       16.0   12.0
87           88  110.7   40.6       63.2   16.0
88           89   88.3   25.5       73.4   12.9
89           90  109.8   47.8       51.4   16.7
90           91  134.3    4.9        9.3   11.2
91           92   28.6    1.5       33.0    7.3
92           93  217.7   33.5       59.0   19.4
93           94  250.9   36.5       72.3   22.2
94           95  107.4   14.0       10.9   11.5
95           96  163.3   31.6       52.9   16.9
96           97  197.6    3.5        5.9   11.7
97           98  184.9   21.0       22.0   15.5
98           99  289.7   42.3       51.2   25.4
99          100  135.2   41.7       45.9   17.2
100         101  222.4    4.3       49.8   11.7
101         102  296.4   36.3      100.9   23.8
102         103  280.2   10.1       21.4   14.8
103         104  187.9   17.2       17.9   14.7
104         105  238.2   34.3        5.3   20.7
105         106  137.9   46.4       59.0   19.2
106         107   25.0   11.0       29.7    7.2
107         108   90.4    0.3       23.2    8.7
108         109   13.1    0.4       25.6    5.3
109         110  255.4   26.9        5.5   19.8
110         111  225.8    8.2       56.5   13.4
111         112  241.7   38.0       23.2   21.8
112         113  175.7   15.4        2.4   14.1
113         114  209.6   20.6       10.7   15.9
114         115   78.2   46.8       34.5   14.6
115         116   75.1   35.0       52.7   12.6
116         117  139.2   14.3       25.6   12.2
117         118   76.4    0.8       14.8    9.4
118         119  125.7   36.9       79.2   15.9
119         120   19.4   16.0       22.3    6.6
120         121  141.3   26.8       46.2   15.5
121         122   18.8   21.7       50.4    7.0
122         123  224.0    2.4       15.6   11.6
123         124  123.1   34.6       12.4   15.2
124         125  229.5   32.3       74.2   19.7
125         126   87.2   11.8       25.9   10.6
126         127    7.8   38.9       50.6    6.6
127         128   80.2    0.0        9.2    8.8
128         129  220.3   49.0        3.2   24.7
129         130   59.6   12.0       43.1    9.7
130         131    0.7   39.6        8.7    1.6
131         132  265.2    2.9       43.0   12.7
132         133    8.4   27.2        2.1    5.7
133         134  219.8   33.5       45.1   19.6
134         135   36.9   38.6       65.6   10.8
135         136   48.3   47.0        8.5   11.6
136         137   25.6   39.0        9.3    9.5
137         138  273.7   28.9       59.7   20.8
138         139   43.0   25.9       20.5    9.6
139         140  184.9   43.9        1.7   20.7
140         141   73.4   17.0       12.9   10.9
141         142  193.7   35.4       75.6   19.2
142         143  220.5   33.2       37.9   20.1
143         144  104.6    5.7       34.4   10.4
144         145   96.2   14.8       38.9   11.4
145         146  140.3    1.9        9.0   10.3
146         147  240.1    7.3        8.7   13.2
147         148  243.2   49.0       44.3   25.4
148         149   38.0   40.3       11.9   10.9
149         150   44.7   25.8       20.6   10.1
150         151  280.7   13.9       37.0   16.1
151         152  121.0    8.4       48.7   11.6
152         153  197.6   23.3       14.2   16.6
153         154  171.3   39.7       37.7   19.0
154         155  187.8   21.1        9.5   15.6
155         156    4.1   11.6        5.7    3.2
156         157   93.9   43.5       50.5   15.3
157         158  149.8    1.3       24.3   10.1
158         159   11.7   36.9       45.2    7.3
159         160  131.7   18.4       34.6   12.9
160         161  172.5   18.1       30.7   14.4
161         162   85.7   35.8       49.3   13.3
162         163  188.4   18.1       25.6   14.9
163         164  163.5   36.8        7.4   18.0
164         165  117.2   14.7        5.4   11.9
165         166  234.5    3.4       84.8   11.9
166         167   17.9   37.6       21.6    8.0
167         168  206.8    5.2       19.4   12.2
168         169  215.4   23.6       57.6   17.1
169         170  284.3   10.6        6.4   15.0
170         171   50.0   11.6       18.4    8.4
171         172  164.5   20.9       47.4   14.5
172         173   19.6   20.1       17.0    7.6
173         174  168.4    7.1       12.8   11.7
174         175  222.4    3.4       13.1   11.5
175         176  276.9   48.9       41.8   27.0
176         177  248.4   30.2       20.3   20.2
177         178  170.2    7.8       35.2   11.7
178         179  276.7    2.3       23.7   11.8
179         180  165.6   10.0       17.6   12.6
180         181  156.6    2.6        8.3   10.5
181         182  218.5    5.4       27.4   12.2
182         183   56.2    5.7       29.7    8.7
183         184  287.6   43.0       71.8   26.2
184         185  253.8   21.3       30.0   17.6
185         186  205.0   45.1       19.6   22.6
186         187  139.5    2.1       26.6   10.3
187         188  191.1   28.7       18.2   17.3
188         189  286.0   13.9        3.7   15.9
189         190   18.7   12.1       23.4    6.7
190         191   39.5   41.1        5.8   10.8
191         192   75.5   10.8        6.0    9.9
192         193   17.2    4.1       31.6    5.9
193         194  166.8   42.0        3.6   19.6
194         195  149.7   35.6        6.0   17.3
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [48]:
print(dataf2)

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
5             6    8.7   48.9       75.0    7.2
6             7   57.5   32.8       23.5   11.8
7             8  120.2   19.6       11.6   13.2
8             9    8.6    2.1        1.0    4.8
9            10  199.8    2.6       21.2   10.6
10           11   66.1    5.8       24.2    8.6
11           12  214.7   24.0        4.0   17.4
12           13   23.8   35.1       65.9    9.2
13           14   97.5    7.6        7.2    9.7
14           15  204.1   32.9       46.0   19.0
15           16  195.4   47.7       52.9   22.4
16           17   67.8   36.6      114.0   12.5
17           18  281.4   39.6       55.8   24.4
18           19   69.2   20.5       18.3   11.3
19           20  147.3   23.9       19.1   14.6
20           21  218.4   27.7       53.4   18.0
21           22  237.4    5.1       23.5   12.5
22           23   13.2   15.9       49.6    5.6
23           24  228.3   16.9       26.2   15.5
24           25   62.3   12.6       18.3    9.7
25           26  262.9    3.5       19.5   12.0
26           27  142.9   29.3       12.6   15.0
27           28  240.1   16.7       22.9   15.9
28           29  248.8   27.1       22.9   18.9
29           30   70.6   16.0       40.8   10.5
30           31  292.9   28.3       43.2   21.4
31           32  112.9   17.4       38.6   11.9
32           33   97.2    1.5       30.0    9.6
33           34  265.6   20.0        0.3   17.4
34           35   95.7    1.4        7.4    9.5
35           36  290.7    4.1        8.5   12.8
36           37  266.9   43.8        5.0   25.4
37           38   74.7   49.4       45.7   14.7
38           39   43.1   26.7       35.1   10.1
39           40  228.0   37.7       32.0   21.5
40           41  202.5   22.3       31.6   16.6
41           42  177.0   33.4       38.7   17.1
42           43  293.6   27.7        1.8   20.7
43           44  206.9    8.4       26.4   12.9
44           45   25.1   25.7       43.3    8.5
45           46  175.1   22.5       31.5   14.9
46           47   89.7    9.9       35.7   10.6
47           48  239.9   41.5       18.5   23.2
48           49  227.2   15.8       49.9   14.8
49           50   66.9   11.7       36.8    9.7
50           51  199.8    3.1       34.6   11.4
51           52  100.4    9.6        3.6   10.7
52           53  216.4   41.7       39.6   22.6
53           54  182.6   46.2       58.7   21.2
54           55  262.7   28.8       15.9   20.2
55           56  198.9   49.4       60.0   23.7
56           57    7.3   28.1       41.4    5.5
57           58  136.2   19.2       16.6   13.2
58           59  210.8   49.6       37.7   23.8
59           60  210.7   29.5        9.3   18.4
60           61   53.5    2.0       21.4    8.1
61           62  261.3   42.7       54.7   24.2
62           63  239.3   15.5       27.3   15.7
63           64  102.7   29.6        8.4   14.0
64           65  131.1   42.8       28.9   18.0
65           66   69.0    9.3        0.9    9.3
66           67   31.5   24.6        2.2    9.5
67           68  139.3   14.5       10.2   13.4
68           69  237.4   27.5       11.0   18.9
69           70  216.8   43.9       27.2   22.3
70           71  199.1   30.6       38.7   18.3
71           72  109.8   14.3       31.7   12.4
72           73   26.8   33.0       19.3    8.8
73           74  129.4    5.7       31.3   11.0
74           75  213.4   24.6       13.1   17.0
75           76   16.9   43.7       89.4    8.7
76           77   27.5    1.6       20.7    6.9
77           78  120.5   28.5       14.2   14.2
78           79    5.4   29.9        9.4    5.3
79           80  116.0    7.7       23.1   11.0
80           81   76.4   26.7       22.3   11.8
81           82  239.8    4.1       36.9   12.3
82           83   75.3   20.3       32.5   11.3
83           84   68.4   44.5       35.6   13.6
84           85  213.5   43.0       33.8   21.7
85           86  193.2   18.4       65.7   15.2
86           87   76.3   27.5       16.0   12.0
87           88  110.7   40.6       63.2   16.0
88           89   88.3   25.5       73.4   12.9
89           90  109.8   47.8       51.4   16.7
90           91  134.3    4.9        9.3   11.2
91           92   28.6    1.5       33.0    7.3
92           93  217.7   33.5       59.0   19.4
93           94  250.9   36.5       72.3   22.2
94           95  107.4   14.0       10.9   11.5
95           96  163.3   31.6       52.9   16.9
96           97  197.6    3.5        5.9   11.7
97           98  184.9   21.0       22.0   15.5
98           99  289.7   42.3       51.2   25.4
99          100  135.2   41.7       45.9   17.2
100         101  222.4    4.3       49.8   11.7
101         102  296.4   36.3      100.9   23.8
102         103  280.2   10.1       21.4   14.8
103         104  187.9   17.2       17.9   14.7
104         105  238.2   34.3        5.3   20.7
105         106  137.9   46.4       59.0   19.2
106         107   25.0   11.0       29.7    7.2
107         108   90.4    0.3       23.2    8.7
108         109   13.1    0.4       25.6    5.3
109         110  255.4   26.9        5.5   19.8
110         111  225.8    8.2       56.5   13.4
111         112  241.7   38.0       23.2   21.8
112         113  175.7   15.4        2.4   14.1
113         114  209.6   20.6       10.7   15.9
114         115   78.2   46.8       34.5   14.6
115         116   75.1   35.0       52.7   12.6
116         117  139.2   14.3       25.6   12.2
117         118   76.4    0.8       14.8    9.4
118         119  125.7   36.9       79.2   15.9
119         120   19.4   16.0       22.3    6.6
120         121  141.3   26.8       46.2   15.5
121         122   18.8   21.7       50.4    7.0
122         123  224.0    2.4       15.6   11.6
123         124  123.1   34.6       12.4   15.2
124         125  229.5   32.3       74.2   19.7
125         126   87.2   11.8       25.9   10.6
126         127    7.8   38.9       50.6    6.6
127         128   80.2    0.0        9.2    8.8
128         129  220.3   49.0        3.2   24.7
129         130   59.6   12.0       43.1    9.7
130         131    0.7   39.6        8.7    1.6
131         132  265.2    2.9       43.0   12.7
132         133    8.4   27.2        2.1    5.7
133         134  219.8   33.5       45.1   19.6
134         135   36.9   38.6       65.6   10.8
135         136   48.3   47.0        8.5   11.6
136         137   25.6   39.0        9.3    9.5
137         138  273.7   28.9       59.7   20.8
138         139   43.0   25.9       20.5    9.6
139         140  184.9   43.9        1.7   20.7
140         141   73.4   17.0       12.9   10.9
141         142  193.7   35.4       75.6   19.2
142         143  220.5   33.2       37.9   20.1
143         144  104.6    5.7       34.4   10.4
144         145   96.2   14.8       38.9   11.4
145         146  140.3    1.9        9.0   10.3
146         147  240.1    7.3        8.7   13.2
147         148  243.2   49.0       44.3   25.4
148         149   38.0   40.3       11.9   10.9
149         150   44.7   25.8       20.6   10.1
150         151  280.7   13.9       37.0   16.1
151         152  121.0    8.4       48.7   11.6
152         153  197.6   23.3       14.2   16.6
153         154  171.3   39.7       37.7   19.0
154         155  187.8   21.1        9.5   15.6
155         156    4.1   11.6        5.7    3.2
156         157   93.9   43.5       50.5   15.3
157         158  149.8    1.3       24.3   10.1
158         159   11.7   36.9       45.2    7.3
159         160  131.7   18.4       34.6   12.9
160         161  172.5   18.1       30.7   14.4
161         162   85.7   35.8       49.3   13.3
162         163  188.4   18.1       25.6   14.9
163         164  163.5   36.8        7.4   18.0
164         165  117.2   14.7        5.4   11.9
165         166  234.5    3.4       84.8   11.9
166         167   17.9   37.6       21.6    8.0
167         168  206.8    5.2       19.4   12.2
168         169  215.4   23.6       57.6   17.1
169         170  284.3   10.6        6.4   15.0
170         171   50.0   11.6       18.4    8.4
171         172  164.5   20.9       47.4   14.5
172         173   19.6   20.1       17.0    7.6
173         174  168.4    7.1       12.8   11.7
174         175  222.4    3.4       13.1   11.5
175         176  276.9   48.9       41.8   27.0
176         177  248.4   30.2       20.3   20.2
177         178  170.2    7.8       35.2   11.7
178         179  276.7    2.3       23.7   11.8
179         180  165.6   10.0       17.6   12.6
180         181  156.6    2.6        8.3   10.5
181         182  218.5    5.4       27.4   12.2
182         183   56.2    5.7       29.7    8.7
183         184  287.6   43.0       71.8   26.2
184         185  253.8   21.3       30.0   17.6
185         186  205.0   45.1       19.6   22.6
186         187  139.5    2.1       26.6   10.3
187         188  191.1   28.7       18.2   17.3
188         189  286.0   13.9        3.7   15.9
189         190   18.7   12.1       23.4    6.7
190         191   39.5   41.1        5.8   10.8
191         192   75.5   10.8        6.0    9.9
192         193   17.2    4.1       31.6    5.9
193         194  166.8   42.0        3.6   19.6
194         195  149.7   35.6        6.0   17.3
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [49]:
dataf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [50]:
dataf2.describe()

       Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [51]:
print(dataf2[['Unnamed: 0','TV']])

     Unnamed: 0     TV
0             1  230.1
1             2   44.5
2             3   17.2
3             4  151.5
4             5  180.8
5             6    8.7
6             7   57.5
7             8  120.2
8             9    8.6
9            10  199.8
10           11   66.1
11           12  214.7
12           13   23.8
13           14   97.5
14           15  204.1
15           16  195.4
16           17   67.8
17           18  281.4
18           19   69.2
19           20  147.3
20           21  218.4
21           22  237.4
22           23   13.2
23           24  228.3
24           25   62.3
25           26  262.9
26           27  142.9
27           28  240.1
28           29  248.8
29           30   70.6
30           31  292.9
31           32  112.9
32           33   97.2
33           34  265.6
34           35   95.7
35           36  290.7
36           37  266.9
37           38   74.7
38           39   43.1
39           40  228.0
40           41  202.5
41           42  177.0
42           43  293.6
43           44  206.9
44           45   25.1
45           46  175.1
46           47   89.7
47           48  239.9
48           49  227.2
49           50   66.9
50           51  199.8
51           52  100.4
52           53  216.4
53           54  182.6
54           55  262.7
55           56  198.9
56           57    7.3
57           58  136.2
58           59  210.8
59           60  210.7
60           61   53.5
61           62  261.3
62           63  239.3
63           64  102.7
64           65  131.1
65           66   69.0
66           67   31.5
67           68  139.3
68           69  237.4
69           70  216.8
70           71  199.1
71           72  109.8
72           73   26.8
73           74  129.4
74           75  213.4
75           76   16.9
76           77   27.5
77           78  120.5
78           79    5.4
79           80  116.0
80           81   76.4
81           82  239.8
82           83   75.3
83           84   68.4
84           85  213.5
85           86  193.2
86           87   76.3
87           88  110.7
88           89   88.3
89           90  109.8
90           91  134.3
91           92   28.6
92           93  217.7
93           94  250.9
94           95  107.4
95           96  163.3
96           97  197.6
97           98  184.9
98           99  289.7
99          100  135.2
100         101  222.4
101         102  296.4
102         103  280.2
103         104  187.9
104         105  238.2
105         106  137.9
106         107   25.0
107         108   90.4
108         109   13.1
109         110  255.4
110         111  225.8
111         112  241.7
112         113  175.7
113         114  209.6
114         115   78.2
115         116   75.1
116         117  139.2
117         118   76.4
118         119  125.7
119         120   19.4
120         121  141.3
121         122   18.8
122         123  224.0
123         124  123.1
124         125  229.5
125         126   87.2
126         127    7.8
127         128   80.2
128         129  220.3
129         130   59.6
130         131    0.7
131         132  265.2
132         133    8.4
133         134  219.8
134         135   36.9
135         136   48.3
136         137   25.6
137         138  273.7
138         139   43.0
139         140  184.9
140         141   73.4
141         142  193.7
142         143  220.5
143         144  104.6
144         145   96.2
145         146  140.3
146         147  240.1
147         148  243.2
148         149   38.0
149         150   44.7
150         151  280.7
151         152  121.0
152         153  197.6
153         154  171.3
154         155  187.8
155         156    4.1
156         157   93.9
157         158  149.8
158         159   11.7
159         160  131.7
160         161  172.5
161         162   85.7
162         163  188.4
163         164  163.5
164         165  117.2
165         166  234.5
166         167   17.9
167         168  206.8
168         169  215.4
169         170  284.3
170         171   50.0
171         172  164.5
172         173   19.6
173         174  168.4
174         175  222.4
175         176  276.9
176         177  248.4
177         178  170.2
178         179  276.7
179         180  165.6
180         181  156.6
181         182  218.5
182         183   56.2
183         184  287.6
184         185  253.8
185         186  205.0
186         187  139.5
187         188  191.1
188         189  286.0
189         190   18.7
190         191   39.5
191         192   75.5
192         193   17.2
193         194  166.8
194         195  149.7
195         196   38.2
196         197   94.2
197         198  177.0
198         199  283.6
199         200  232.1

In [52]:
dataf2.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [53]:
dataf2.tail()

     Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [54]:
print(sts.mode(dataf2['Sales']))
print(sts.mean(dataf2['Sales']))
print(sts.median(dataf2['Sales']))

9.7
14.022499999999999
12.9

# Introduction to Numpy
## 23/7/24

In [55]:
import numpy as np

In [56]:
print(np.__version__)

1.26.4

In [57]:
arr = np.arange(1,100)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [58]:
print(type(arr))

<class 'numpy.ndarray'>

In [59]:
arr2=[21,89,34,67,96,96]
arr2

[21, 89, 34, 67, 96, 96]

In [60]:
print(np.mean(arr2))

67.16666666666667

In [61]:
print(np.median(arr2))

78.0

# 24/7/24

In [62]:
import statistics as sts
sample = [2.74,1.23,2.63,2.22,1.90]
print(sample)

[2.74, 1.23, 2.63, 2.22, 1.9]

In [63]:
print(sts.variance(sample))

0.3730300000000001

In [64]:
print(sts.stdev([1,3,5,7,9]))
print(sts.stdev(sample))

3.1622776601683795
0.6107618193698752

In [65]:
print(sts.mode([1,3,5,7,9]))
print(sts.mode(sample))

1
2.74